package es.upm.miw.devops.domain.model;

public enum Province {
    ALAVA, ALBACETE, ALICANTE, ALMERIA, AVILA, BADAJOZ, BALEARES, BARCELONA, BURGOS,
    CACERES, CADIZ, CASTELLON, CIUDAD_REAL, CORDOBA, CORUNA, CUENCA, GIRONA, GRANADA,
    GUADALAJARA, GIPUZKOA, HUELVA, HUESCA, JAEN, LEON, LLEIDA, LUGO, MADRID, MALAGA,
    MURCIA, NAVARRA, OURENSE, ASTURIAS, PALENCIA, LAS_PALMAS, PONTEVEDRA, SALAMANCA,
    SANTA_CRUZ_DE_TENERIFE, CANTABRIA, SEGOVIA, SEVILLA, SORIA, TARRAGONA, TERUEL,
    TOLEDO, VALENCIA, VALLADOLID, BIZKAIA, ZAMORA, ZARAGOZA, CEUTA, MELILLA
}
